# Generated by Django 3.2.5 on 2021-07-15 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210715_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sku',
        ),
        migrations.AddField(
            model_name='products',
            name='product_alert',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
