# Generated by Django 3.2.5 on 2021-07-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210715_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_alert',
            field=models.CharField(max_length=9999999),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=9999999),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(default=1, max_length=9999999),
            preserve_default=False,
        ),
    ]
