# Generated by Django 3.2.5 on 2021-07-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_products_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_alert',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='sku',
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['sku'], name='item_produc_sku_fc3125_idx'),
        ),
    ]
